# Generated by Django 4.2.7 on 2025-10-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('kaspi', 'Kaspi'), ('card', 'Банковская карта'), ('cash', 'Наличные')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('qr_data', models.TextField(blank=True)),
                ('payment_url', models.URLField(blank=True)),
                ('kaspi_payment_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
